### ISSUE TITLE
milianw.de error -- can't retrieve the librarie

### ISSUE THREAD

**Issue by noraj** [lukaswhite/Drupal-Markdownify#1]
Markdownify project page on millianw.de is down
http://milianw.de/projects/markdownify/
Serving a php error :
 Fatal error: Call-time pass-by-reference has been removed in /www/htdocs/w0065fc9/milianw/projects/markdownify/index.php on line 81

**Comment by lukaswhite** [comment]
That's an issue for the project's maintainer, not this library.
