### ISSUE TITLE
Broken download link to http://milianw.de/projects/markdownify/

### ISSUE THREAD

**Issue by jessp01** [lukaswhite/Drupal-Markdownify#2]
Hi there,

First of all, great job with this and https://github.com/lukaswhite/Drupal-Jekyll-Export, saved me a lot of work!
Second, when going to http://milianw.de/projects/markdownify/, one currently gets:
 Fatal error: Call-time pass-by-reference has been removed in /www/htdocs/w0065fc9/milianw/projects/markdownify/index.php on line 81

I suggest you change to README to note it should be downloaded from https://sourceforge.net/projects/markdownify/files/latest/

Thanks again,

**Comment by lukaswhite** [comment]
Glad you found it useful!

Thanks for the updated download location, I've updated the README accordingly.
